### ISSUE TITLE
Feature request: Long press - for continuous touch

### ISSUE THREAD

**Issue by KlavsKlavsen** [Nitrokey/nitrokey-fido-u2f-firmware#14]
One issue - which annoys a lot of us, when using touch mode (which is a LOT safer) - is that we use
https://www.passwordstore.org/  - which keeps each password in its own file - and gpg encrypts that file.
That works great - and when touch is required for each operation, no one can steal my passwords - as it'll just 'blink' and wait for my touch..

However.. for certain operations.. we really would like a way to "longpress".. or "auto touch" for multiple gpg operations..

f.ex. When we want to run ansible (remote operations) on 100+ machines (that only takes ~5-10 seconds to login to them all ) 

or when I need to reencrypt my passwordstore (to give access to another employee - or remove ones access) - since both times, I need to touch for EVERY server|password. 

I would like to be able to setup so "touch for x times.. or for X amount of time.." - enabled "longpress" - where the nitrokey will "act as if I am still touching it" for ~10 seconds or so - giving me time to do the operations I need to, without having to touch for every single one (ie. disabling fix setting for that specific operation type (sign, encrypt.. )) for that small timeperiod..

**Comment by rugk** [comment]
> that we use passwordmanager.org http://passwordmanager.org 

Totally off-topic, but I had a look at their site and **not only was that thing last updated in 2015**, but they also state:

> SunJCE crypto (specifically DES 56-bit encryption with a 1024 bit MD5 hash algorithm)

…which is horrible crypto. MD5 is broken since years, same for DES! E.g. already in 1996 some issues were found in MD5 and people recommend switching away from it. This DES has been cracked in 1998. (Just read the Wikipedia articles. These numbers are directly from there.) Nowadays there are even online services for cracking DES in a matter of a day or so… You literally just cannot use DES anymore, nowadays!

So this is literally the worst password-manager I've ever seen, just reading these first few sentences you can judge the security. So the best idea/thing you can now do is: **Stop using this**. Now! And migrate to a secure password manager.
If the PW database is leaked, it is very likely decrypted very fast, at least for people with not-so-strong passwords. Basically just consider it to be plaintext you save on your disk. That would be the  As such, you do not even need to think about 2FA or so here, you have much bigger issues.

**Comment by KlavsKlavsen** [comment]
sorry.. wrote the wrong url (embarressing).. its pass ( https://www.passwordstore.org/ ) we're using. It uses GPG behind the scenes.. which is WHY we need to touch the key A LOT - when having to reencrypt the entire store. It wouldn't really make sense to talk about this - if the password manager we used, wasn't built on GPG :)

**Comment by rugk** [comment]
Ahhhh… now it makes a lot more sense. However, still the wrong repo, I guess, as this here is about U2F, not about the Nitrokey with GPG support.

**Comment by KlavsKlavsen** [comment]
You are right..
